apiVersion: apps/v1
kind: Deployment
metadata:
  name: minetest
  labels:
    app: minetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minetest
  template:
    metadata:
      labels:
        app: minetest
    spec:
      containers:
      - name: minetest
        image: skullandbones/minetest
        ports:
        - containerPort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: minetest-service
spec:
  selector:
    app: minetest
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
  type: NodePort
